name: Build Native Libs

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
        description: Version number (package)
      publish:
        type: boolean
        description: Publish package to NuGet

permissions:
  contents: read

jobs:
  build-platforms:
    name: Build ${{ matrix.targetname }}-${{ matrix.arch }}
    runs-on: ${{ matrix.buildos }}

    env:
      ARCHIVE_DIR: ${{ github.workspace }}/archive-${{ matrix.targetname }}-${{ matrix.arch }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - { targetname: osx, buildos: macos-latest, arch: x64, preset: osx-x64, osxarch: x86_64 }
          - { targetname: osx, buildos: macos-latest, arch: arm64, preset: osx-arm64, osxarch: arm64 }
          - { targetname: linux, buildos: ubuntu-22.04, arch: x64, preset: linux-x64 }
          - { targetname: linux, buildos: ubuntu-22.04, arch: arm64, preset: linux-arm64 }
          - { targetname: windows, buildos: windows-latest, arch: x64, preset: windows-x64, msvcarch: x64 }
          - { targetname: windows, buildos: windows-latest, arch: arm64, preset: windows-arm64, msvcarch: ARM64 }

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Prepare Environment (Linux)
        if: matrix.targetname == 'linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-12 g++-12
          if [ "${{ matrix.arch }}" = "arm64" ]; then
            sudo apt-get install -y binutils-aarch64-linux-gnu gcc-12-aarch64-linux-gnu g++-12-aarch64-linux-gnu
          fi

      - name: Prepare Environment (macOS)
        if: matrix.targetname == 'osx'
        run: brew install ninja

      - name: Setup VCPKG
        uses: lukka/run-vcpkg@v11

      - name: Configure (osx)
        if: matrix.targetname == 'osx'
        run: cmake --preset ${{ matrix.preset }} -G Xcode -DCMAKE_OSX_ARCHITECTURES=${{ matrix.osxarch }}

      - name: Configure (linux)
        if: matrix.targetname == 'linux'
        run: cmake --preset ${{ matrix.preset }}

      - name: Configure (windows)
        if: matrix.targetname == 'windows'
        run: cmake --preset ${{ matrix.preset }} -A ${{ matrix.msvcarch }}

      - name: Build
        run: cmake --build build --config Release

      - name: Prepare Directory
        run: mkdir -p ${{ env.ARCHIVE_DIR }}

      - name: Collect Artifacts (Linux)
        if: matrix.targetname == 'linux'
        run: cp build/libtsw.so ${{ env.ARCHIVE_DIR }}

      - name: Collect Artifacts (osx)
        if: matrix.targetname == 'osx'
        run: cp build/Release/libtsw.dylib ${{ env.ARCHIVE_DIR }}

      - name: Collect Artifacts (windows)
        if: matrix.targetname == 'windows'
        run: cp build/Release/*.dll ${{ env.ARCHIVE_DIR }}

      - name: Upload
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.targetname }}-${{ matrix.arch }}
          path: ${{ env.ARCHIVE_DIR }}/*

  package:
    name: Build Package
    runs-on: ubuntu-latest
    needs: [build-platforms]

    steps:
      - uses: actions/checkout@v7

      - uses: actions/download-artifact@v8
        with: { name: osx-x64, path: native/nuget/runtimes/osx-x64/native }

      - uses: actions/download-artifact@v8
        with: { name: osx-arm64, path: native/nuget/runtimes/osx-arm64/native }

      - uses: actions/download-artifact@v8
        with: { name: windows-x64, path: native/nuget/runtimes/win-x64/native }

      - uses: actions/download-artifact@v8
        with: { name: windows-arm64, path: native/nuget/runtimes/win-arm64/native }

      - uses: actions/download-artifact@v8
        with: { name: linux-x64, path: native/nuget/runtimes/linux-x64/native }

      - uses: actions/download-artifact@v8
        with: { name: linux-arm64, path: native/nuget/runtimes/linux-arm64/native }

      - name: Build Package
        run: dotnet pack -c Release -p:Version=${{ github.event.inputs.version }} -o ./packages native/nuget

      - name: Publish Package (NuGet)
        if: github.event.inputs.publish == 'true'
        run: dotnet nuget push -s https://api.nuget.org/v3/index.json --skip-duplicate -k ${{ secrets.NUGET_KEY }} ./packages/*.nupkg

      - name: Upload Package (Artifact)
        if: github.event.inputs.publish != 'true'
        uses: actions/upload-artifact@v7
        with:
          name: TorrentSharp.Wrap.Native-${{ github.event.inputs.version }}
          path: ./packages/*
